# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_ctlSettings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ctlSettings(object):
    def setupUi(self, ctlSettings):
        ctlSettings.setObjectName("ctlSettings")
        ctlSettings.resize(422, 288)
        ctlSettings.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(ctlSettings)
        self.buttonBox.setGeometry(QtCore.QRect(70, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ctlSettings)
        self.label.setGeometry(QtCore.QRect(20, 50, 71, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.port = QtWidgets.QLineEdit(ctlSettings)
        self.port.setGeometry(QtCore.QRect(90, 60, 113, 20))
        self.port.setObjectName("port")
        self.password = QtWidgets.QLineEdit(ctlSettings)
        self.password.setGeometry(QtCore.QRect(290, 60, 113, 20))
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(ctlSettings)
        self.label_2.setGeometry(QtCore.QRect(220, 50, 71, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(ctlSettings)
        self.frame.setGeometry(QtCore.QRect(10, 20, 401, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 54, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(ctlSettings)
        self.frame_2.setGeometry(QtCore.QRect(10, 110, 401, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 54, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(240, 39, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 39, 111, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 39, 101, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 99, 271, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 69, 271, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.label.raise_()
        self.port.raise_()
        self.password.raise_()
        self.label_2.raise_()
        self.frame_2.raise_()

        self.retranslateUi(ctlSettings)
        self.buttonBox.accepted.connect(ctlSettings.accept)
        self.buttonBox.rejected.connect(ctlSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(ctlSettings)

    def retranslateUi(self, ctlSettings):
        _translate = QtCore.QCoreApplication.translate
        ctlSettings.setWindowTitle(_translate("ctlSettings", "Dialog"))
        self.label.setText(_translate("ctlSettings", "监听端口："))
        self.port.setText(_translate("ctlSettings", "443"))
        self.password.setText(_translate("ctlSettings", "Passw0rd"))
        self.label_2.setText(_translate("ctlSettings", "密   码："))
        self.label_3.setText(_translate("ctlSettings", "本地配置"))
        self.label_4.setText(_translate("ctlSettings", "远程配置"))
        self.label_5.setText(_translate("ctlSettings", "限制权限Token："))
        self.label_6.setText(_translate("ctlSettings", "密码："))
        self.label_7.setText(_translate("ctlSettings", "管理权限Token："))
        self.label_8.setText(_translate("ctlSettings", "Github平台账户："))

